### ISSUE TITLE
Error Code: 403 when I tried to post a request

### ISSUE THREAD

**Issue by Shyee7** [clintcarr/nppy#1]
{
    "title": "Forbidden",
    "description": "REVEL_CSRF: tokens mismatch."
}
I tried to add  a header named 'X-XSRF-TOKEN' but it doesn't work, please see details in the community:
https://community.qlik.com/thread/242608 

headers = {"Accept": "application/json",
            "Content-Type": "application/json",
            **"X-XSRF-TOKEN": "y2I7svcZLjJIJHLC8TTRO15YyRqW0HRTtDKkAr6Msgo="**}
The value of 'X-XSRF-TOKEN' is from 'NPWEBCONSOLE_XSRF-TOKEN' in cookies.

**Comment by clintcarr** [comment]
The APIS for nPrinting have changed substantially and I have not updated this wrapper.
Apologies, will have a look over the coming days.

**Comment by vinayajo** [comment]
after added xsrf token. i am getting response code as 502 for nPrinting ondemandrequests

 def post_ondemandrequest(self, reportid = None):
        print (" report id" + reportid)
        path = 'ondemand/requests'
        data = {'type': 'report',
                'config': {'reportId': reportid},
                            'outputFormat': 'PDF'}
        json_data= json.dumps(data)
        return self.post(path, json_data)

**Comment by clintcarr** [comment]
The APIS have changed substantially.  As such this wrapper is obsolete until I update it.
Please review the documentation at help.qlik.com

**Comment by vinayajo** [comment]
thanks. sorry to ask this  when we will get this, that should be very useful to us do some automation
